name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch country-codes
      run: |-
        curl --create-dirs -O --output-dir data/ https://raw.githubusercontent.com/datasets/country-codes/master/data/country-codes.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push